### ISSUE TITLE
Consider changing autocomplete to any of the keyword words?

### ISSUE THREAD

**Issue by kg-currenxie** [zeddz92/react-emoji-search#16]
Hi :)

![image](https://github.com/iamcal/emoji-data/assets/48229166/72743da9-df92-44c6-940e-4baa693312c2)
this one is `face_with_open_eyes_and_hand_over_mouth`
or in your data file: 
`{ keywords: ["face with hand over mouth", "whoops"] }`

i couldnt find a way to search for it:
![image](https://github.com/iamcal/emoji-data/assets/48229166/5dc11d78-5b58-4a4c-8e8d-7023d63135cc)
![image](https://github.com/iamcal/emoji-data/assets/48229166/6cf06090-c351-496e-9180-2e9d38bdf87d)
![image](https://github.com/iamcal/emoji-data/assets/48229166/b7c7998a-41c6-4993-abf8-403c53445a7b)
![image](https://github.com/iamcal/emoji-data/assets/48229166/ecb0f06d-70ed-4e99-aabc-9297fdb6e0f2)

eventually by looking at the code, i realised it can be searched by a spaces:
![image](https://github.com/zeddz92/react-emoji-search/assets/48229166/543f10ae-de3b-4cf2-8d76-b28fffbbe551)
but tbh, its not really obvious :)

especially when other pickers dont use spaces. here's slack for example:
![image](https://github.com/zeddz92/react-emoji-search/assets/48229166/e6f8ffdf-29a2-49b1-b244-0eabd7c5ec9e)

it can also search for any of the words:
![image](https://github.com/zeddz92/react-emoji-search/assets/48229166/c107dbc2-79fa-40d1-b741-f284ee933b60)

which is easier to guess alot of the time, than typing "face with"

so the autocomplete is:
```
emoji.keywords.some((word: string) => word.startsWith(text))
```

would you consider changing to `word.includes(text)` ?

----

yours also does not have any way to see the keywords, so you can't go through the grid and learn. consider adding a tooltip to display the keywords?

even something "stupid and simple" like the html `title` attribute:
![image](https://github.com/zeddz92/react-emoji-search/assets/48229166/68ed37e9-ca73-4172-9c50-b91bff3db1c4)
unless you wanna make a fancy one

thanks :)

**Comment by zeddz92** [comment]
Hi kg,
Thanks for the feedback. I've made a MR with your suggested changes [here ](https://github.com/zeddz92/react-emoji-search/pull/17). Could you check and see if it's missing something you mentioned?

**Comment by kg-currenxie** [comment]
> Hi kg,
> 
> Thanks for the feedback. I've made a MR with your suggested changes [here ](https://github.com/zeddz92/react-emoji-search/pull/17). Could you check and see if it's missing something you mentioned?

That looks awesome! 😁

**Comment by zeddz92** [comment]
> > Hi kg,
> > Thanks for the feedback. I've made a MR with your suggested changes [here ](https://github.com/zeddz92/react-emoji-search/pull/17). Could you check and see if it's missing something you mentioned?
> 
> That looks awesome! 😁

It's merged!

**Comment by zeddz92** [comment]
> > Hi kg,
> > Thanks for the feedback. I've made a MR with your suggested changes [here ](https://github.com/zeddz92/react-emoji-search/pull/17). Could you check and see if it's missing something you mentioned?
> 
> That looks awesome! 😁

Changes are in version 2.2.27
